name: tms_risk_cuda
channels:
  - conda-forge
  - nvidia
dependencies:
  - python=3.10  # Explicitly set Python version
  - pymc=5.17
  - bambi=0.13
  - compilers  # This is a meta-package; if not found, remove or replace with specific compilers
  - arviz=0.20
  - notebook
  - seaborn
  - pandas
  - numpy=1.25
  - scipy
  - nilearn
  - tqdm
  - cudatoolkit=12.3  # Use 12.3 for TF 2.18
  - cudnn=8.9.2
  - pip
  - pip:
      - -e .
      - ./libs/braincoder
      - ./libs/bauer
      - tensorflow==2.18.0
      - tensorflow-probability
      - tf-keras
