name: tms_risk_cuda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9  # Use a widely available version
  - pip
  - numpy=1.22  # Compatible with Python 3.9 and most packages
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - statsmodels
  - lxml
  - notebook
  - pip:
      - pymc==5.8.1  # Older version with fewer dependencies
      - bambi==0.12.0
      - arviz==0.15.1
      - nilearn
      - tqdm
      - tensorflow==2.10.0  # Older, but widely compatible
      - tensorflow-probability==0.18.0
      - tf-keras
      - -e .
      - ./libs/braincoder
      - ./libs/bauer
